---
title: "SC306 Homework 3: R Intro Part 2"
author: "Othar Zaldastani II"
date: "February 27, 2026"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
header-includes:
- \usepackage{xcolor}
- \makeatletter
- \providecommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{1}}
- \makeatother
- \usepackage{float}
---

```{r setup, echo=TRUE, results='hide', message=FALSE, warning=FALSE, include = F}
knitr::opts_chunk$set(fig.pos = "H", message = FALSE, warning = FALSE)
library(tidyverse)
library(dplyr)
library(datasets)
```

## Question 1

```{r}
vector.raw = rnorm(1000,mean = 0, sd = 1)

vector.clean = vector.raw[!(vector.raw >= 0 & vector.raw <= 1.5)]
hist(vector.clean)
```



## Question 2
```{r}
vector.1_100 = abs(abs(-99:99)-100)
vector.1_100
```


## Question 3


```{r}
us_sorted = USArrests[order(USArrests$Murder, decreasing = TRUE),]
View(us_sorted)
```

## Question 4

```{r}
USArrests$Urban.Cat = cut(USArrests$UrbanPop,3, labels = c("Low", "Med", "High"))
```


## Question 5
